#!/bin/bash

# SkillBridge AI - Quick Deployment Commands
# ==========================================

echo "🚀 SkillBridge AI - Quick Deployment Reference"
echo "=============================================="
echo ""
echo "📋 Pre-Deployment Checklist:"
echo "  ✅ TypeScript errors fixed"
echo "  ✅ Environment variables documented"
echo "  ✅ Console logs cleaned"
echo "  ✅ Localhost references removed"
echo "  ✅ Vercel configuration ready"
echo ""
echo "🔧 Quick Commands:"
echo ""
echo "1. Commit your changes:"
echo "   git add -A"
echo "   git commit -m \"fix: prepare for Vercel deployment\""
echo "   git push origin main"
echo ""
echo "2. Install Vercel CLI (if needed):"
echo "   npm install -g vercel"
echo ""
echo "3. Deploy to Vercel:"
echo "   vercel"
echo ""
echo "4. Deploy to production:"
echo "   vercel --prod"
echo ""
echo "📝 Environment Variables Needed:"
echo "  - DATABASE_URL"
echo "  - NEXTAUTH_URL (https://your-app.vercel.app)"
echo "  - NEXTAUTH_SECRET"
echo "  - GOOGLE_CLIENT_ID"
echo "  - GOOGLE_CLIENT_SECRET"
echo "  - OPENAI_API_KEY"
echo "  - ELEVENLABS_API_KEY"
echo ""
echo "🔗 Important URLs:"
echo "  - Vercel Dashboard: https://vercel.com/dashboard"
echo "  - Google Console: https://console.cloud.google.com/"
echo "  - Guide: ./VERCEL_DEPLOYMENT_GUIDE.md"
echo ""
echo "Ready to deploy! Good luck! 🎉"
